export const CARUSEL_REQUEST = 'CARUSEL_REQUEST'
export const CARUSEL_SUCCESS = 'CARUSEL_SUCCESS'
export const CARUSEL_FAIL = 'CARUSEL_FAIL'

export const CARUSEL_DETAILS_REQUEST = 'CARUSEL_DETAILS_REQUEST'
export const CARUSEL_DETAILS_SUCCESS = 'CARUSEL_DETAILS_SUCCESS'
export const CARUSEL_DETAILS_FAIL = 'CARUSEL_DETAILS_FAIL'

export const UPDATE_CARUSEL_REQUEST = 'UPDATE_CARUSEL_REQUEST'
export const UPDATE_CARUSEL_SUCCESS = 'UPDATE_CARUSEL_SUCCESS'
export const UPDATE_CARUSEL_FAIL = 'UPDATE_CARUSEL_FAIL'
export const UPDATE_CARUSEL_RESET = 'UPDATE_CARUSEL_RESET'

export const DELETE_CARUSEL_REQUEST = 'DELETE_CARUSEL_REQUEST'
export const DELETE_CARUSEL_SUCCESS = 'DELETE_CARUSEL_SUCCESS'
export const DELETE_CARUSEL_FAIL = 'DELETE_CARUSEL_FAIL'
export const DELETE_CARUSEL_RESET = 'DELETE_CARUSEL_RESET'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'