export const MY_FAV_REQUEST = 'MY_FAV_REQUEST'
export const MY_FAV_SUCCESS = 'MY_FAV_SUCCESS'
export const MY_FAV_FAIL = 'MY_FAV_FAIL'

export const ADD_TO_FAV_REQUEST = 'ADD_TO_FAV_REQUEST'
export const ADD_TO_FAV_SUCCESS = 'ADD_TO_FAV_SUCCESS'
export const ADD_TO_FAV_FAIL = 'ADD_TO_FAV_FAIL'
export const ADD_TO_FAV_RESET = 'ADD_TO_FAV_RESET'

export const REMOVE_FROM_FAV_REQUEST = 'REMOVE_FROM_FAV_REQUEST'
export const REMOVE_FROM_FAV_SUCCESS = 'REMOVE_FROM_FAV_SUCCESS'
export const REMOVE_FROM_FAV_FAIL = 'REMOVE_FROM_FAV_FAIL'
export const REMOVE_FROM_FAV_RESET = 'REMOVE_FROM_FAV_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'